nameREADME: sr
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - cudatoolkit=11.1
  - pytorch=1.8.1
  - torchvision=0.2.2
  - pytorch-lightning=1.2.8
  - geopandas=0.9.0
  - dask=2021.4.0
  - xarray=0.17.0
  - rioxarray=0.3.1
  - cartopy=0.18.0
  - datacube=1.8.3
  - rasterio=1.2.2
  - netCDF4=1.5.6
  - pip
  - pip:
      - -r requirements.txt